builds:
  am:
    composite: 1111131 # FotM_ToF_AS_VT_AM
    dungeons: 1131321 # FotM_SN_SC_MB_AM
    single: 1111131 # FotM_ToF_AS_VT_AM
    conduits:
      first: 
        id: "107"
        name: HA
      second: 
        id: "113"
        name: MD
  hv-as:
    composite: 1111132 # FotM_ToF_AS_VT_HV
    dungeons: 1131122 # FotM_SN_AS_MB_HV
    single: 1111132 # FotM_ToF_AS_VT_HV
    conduits:
      first: 
        id: "115"
        name: DE
      second:
        id: "107"
        name: HA
  hv-sc:
    composite: 1111332 # FotM_ToF_SC_VT_HV
    dungeons: 1131322 # FotM_SN_SC_MB_HV
    single: 1111332 # FotM_ToF_SC_VT_HV
    conduits:
      first:
        id: "115"
        name: DE
      second:
        id: "107"
        name: HA
  stm:
    composite: 1111133 # FotM_ToF_AS_VT_STM
    dungeons: 1131323 # FotM_SN_SC_MB_STM
    single: 1111133 # FotM_ToF_AS_VT_STM
    conduits:
      first:
        id: "107"
        name: HA
      second:
        id: "113"
        name: MD
covenants:
  - kyrian
  - night_fae
  - venthyr
  - necrolord
sims:
  apl:
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  conduit-combos:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files: 
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  conduits:
    builds: true
    weights: false
    covenant: 
      lookup: true
      files: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    files:
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  consumables:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  covenant-choice:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - CovenantRange
    files:
      - choice.simc
  covenants:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  enchants:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  gear:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  legendaries:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - legendaries.simc
  legendary-items:
    builds: true
    weights: false
    covenant: 
      lookup: true
      files: false
    lookupType: spell
    steps:
      - 190
      - 210
      - 225
      - 235
    files:
      - shadow.simc
      - generic.simc
  racials:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  soulbind-traits:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - traits.simc
  soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  soulbinds-launch:
    soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  stats:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - AM.simc
      - HV.simc
      - STM.simc
  trinkets:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: false
    lookupType: item
    steps:
      - 155
      - 158
      - 164
      - 165
      - 170
      - 171
      - 175
      - 177
      - 183
      - 184
      - 187
      - 190
      - 194
      - 195
      - 197
      - 200
      - 203
      - 204
      - 207
      - 210
      - 213
      - 216
      - 220
      - 223
      - 226
      - 233
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    builds: true
    weights: true
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 2
  retryInterval: 20
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 400
  steps: 100
  total: 1400
  include:
    - mastery
    - haste
    - crit
    - versatility
