builds:
  am-as:
    composite: 3121121
    dungeons: 3121121
  stm-as:
    composite: 3121123
    dungeons: 1121113
  am-pl:
    composite: 3121221
    dungeons: 3121221
  stm-pl:
    composite: 3121223
    dungeons: 1121213
covenants:
  - kyrian
  - night_fae
  - venthyr
  - necrolord
sims:
  apl:
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  conduits:
    builds: true
    weights: false
    covenant: 
      lookup: true
      files: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
    files:
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  consumables:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  covenant-choice:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - CovenantRange
    files:
      - choice.simc
  covenants:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  enchants:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  gear:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  legendaries:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - legendaries.simc
  racials:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  soulbinds-launch:
    soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  stats:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - AM.simc
      - LotV.simc
      - STM.simc
  trinkets:
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: item
    steps:
      - 130
      - 135
      - 155
      - 157
      - 165
      - 170
      - 183
      - 187
      - 200
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    builds: true
    weights: true
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 2
  retryInterval: 20
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 400
  steps: 100
  total: 1400
  include:
    - mastery
    - haste
    - crit
    - versatility
