builds:
  am:
    composite: 1111131 # FotM_ToF_AS_VT_AM
    dungeons: 1131321 # FotM_SN_SC_MB_AM
    single: 1111131 # FotM_ToF_AS_VT_AM
    conduits:
      first:
        id: "107"
        name: HA
      second:
        id: "115"
        name: DE
  hv-as:
    composite: 1111132 # FotM_ToF_AS_VT_HV
    dungeons: 1131122 # FotM_SN_AS_MB_HV
    single: 1111132 # FotM_ToF_AS_VT_HV
    conduits:
      first:
        id: "115"
        name: DE
      second:
        id: "107"
        name: HA
  hv-sc:
    composite: 1111332 # FotM_ToF_SC_VT_HV
    dungeons: 1131322 # FotM_SN_SC_MB_HV
    single: 1111332 # FotM_ToF_SC_VT_HV
    conduits:
      first:
        id: "115"
        name: DE
      second:
        id: "107"
        name: HA
  stm:
    composite: 1111133 # FotM_ToF_AS_VT_STM
    dungeons: 1131323 # FotM_SN_SC_MB_STM
    single: 1111133 # FotM_ToF_AS_VT_STM
    conduits:
      first:
        id: "107"
        name: HA
      second:
        id: "115"
        name: DE
covenants:
  list:
    - kyrian
    - night_fae
    - venthyr
    - necrolord
legendary:
    composite: 7162 # Talbadar's Stratagem
    dungeons: 6983 # Eternal Call to the Void
    single: 7162 # Talbadar's Stratagem
sims:
  apl:
    description: "APL Sims used for testing rotational changes only"
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  conduit-combos:
    description: "Sims picking two conduits together to see if this changes the conduit rankings at all."
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files:
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  conduits:
    description: "Conduit sims by rank/ilevel for each given conduit."
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - 145
      - 158
      - 171
      - 184
      - 200
      - 213
      - 226
    files:
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  consumables:
    description: "Sims all consumables you can use to augment your character"
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  covenant-choice:
    description: "This sims all soulbind paths for each covenant and plots them against each other to get the Min (Worst Soulbind) and Max (Best Soulbind) to get a range of DPS you can expect from choosing this Covenant. This is then aggregated and averaged across the various talent options we are currently simming to give a good idea of the performance range you can expect."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - CovenantRange
    files:
      - choice.simc
  covenants:
    description: "This sim takes the soulbinds sim 1 step further and takes the top builds by fight type for each soulbind and adds them with a legendary and the covenant ability to get the actual percent increase for all borrowed power in Shadowlands."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  covenants-launch:
    description: "This sim takes the soulbinds sim 1 step further and takes the top builds by fight type for each soulbind and the covenant ability to get the actual percent increase for all borrowed power in Shadowlands at renown 21."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  covenants-prog:
    description: "This sim takes the soulbinds sim 1 step further and takes the top builds by fight type for each soulbind and adds them with a legendary and the covenant ability to get the actual percent increase for all borrowed power in Shadowlands at renown 22."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  gear:
    description: "NYI"
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: item
    steps:
      - 226
      - 233
    files:
      - t26.simc
  legendaries:
    description: "Adds just the legendary power effect to a piece of gear without changing any other variables. This does not sim the actual legendary item, but just the power to get an idea for the strength of the power specifically."
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - legendaries.simc
  legendary-items:
    description: "Using a base set of Mythic BiS gear from Castle Nathria we swap out for each Legendary Item + Power to get a sense for what would be an upgrade compared to the base pieces we have available. HC stands for Haste Crit, and HM stands for Haste Mastery."
    builds: true
    weights: false
    covenant:
      lookup: true
      files: false
    lookupType: spell
    steps:
      - 190
      - 210
      - 225
      - 235
    files:
      - shadow.simc
      - generic.simc
  racials:
    description: "Swaps out the racial for a particular actor that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  soulbind-traits:
    description: "Individual sims for each soulbind trait + covenant ability from base. Can subtract covenant only effect to see just that increase."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - traits.simc
  soulbinds:
    description: "Sims the various paths for each given soulbind using Rank 7 conduits if selected. Base includes the Covenant ability for that Covenant."
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  soulbinds-launch:
    description: "Altered version of the Soulbinds sim but capped at level 21 renown."
    soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  soulbinds-prog:
    description: "Altered version of the Soulbinds sim but capped at level 22 renown for Mythic Prog time."
    soulbinds:
    builds: true
    weights: false
    covenant:
      lookup: true
      files: true
    lookupType: none
    steps:
      - DPS
    files:
      - necrolord.simc
      - kyrian.simc
      - night_fae.simc
      - venthyr.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims every talent build against each other with no borrowed power."
    builds: false
    weights: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - AM.simc
      - HV.simc
      - STM.simc
  talent-builds:
    description: "Sims various combinations of power with different Talent builds."
    builds: false
    weights: false
    covenant:
      lookup: true
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - builds.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    covenant:
      lookup: true
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket) with base Covenant ability."
    builds: true
    weights: false
    covenant:
      lookup: true
      files: false
    lookupType: item
    steps:
      - 158
      - 161
      - 164
      - 165
      - 168
      - 170
      - 171
      - 174
      - 175
      - 177
      - 181
      - 184
      - 187
      - 190
      - 194
      - 197
      - 200
      - 203
      - 207
      - 210
      - 213
      - 216
      - 220
      - 223
      - 226
      - 233
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for BiS Mythic Castle Nathria gear.
    builds: true
    weights: true
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 10
  retryInterval: 2
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 800
  steps: 100
  total: 1800
  include:
    - mastery
    - haste
    - crit
    - versatility
